services:
  app:
    container_name: invoice-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
      - 9230:9229
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/invoice-db
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - invoice-net

  mongo:
    container_name: mongo-db
    image: mongo:6.0
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - invoice-net

  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - 88:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - invoice-net

volumes:
  mongo-data:
networks:
  invoice-net: