FROM node:lts-alpine3.20 as base

RUN mkdir /app && chown node:node /app
WORKDIR /app

FROM base as dev
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --include=dev

COPY --chown=node:node . .
RUN chown -R node:node /app/node_modules

USER node